define([], function () {
  return {
    "PropertyPaneDescription": "Embed Power Apps Canvas Apps in SharePoint",
    "BasicGroupName": "General",
    "AppWebLinkLabel": "App Web Link",
    "ShowBorderLabel": "Show Border",
    "AspectRatioLabel": "Aspect Ratio",
    "ParametersGroupName": "Parameters",
    "PassingThemeColorsAsParamsLabel": "Passing Theme Palette Colors as Parameters",
    "ParamsLabel": "Manual Parameters",
    "ParamsPanelHeader": "Manual Parameters",
    "ParamsManageBtnLabel": "Manage Parameters",
    "ParamNameLabel": "Name",
    "ParamValueLabel": "Value",
    "UseDynamicPropLabel": "Use Dynamic Property",
    "DynamicPropNameLabel": "Dynamic Property Name",
    "SelectDynamicSourceLabel": "Select Dynamic Source",
    "SelectDynamicPropertyLabel": "Select Dynamic Property",
    "PlaceholderIconText": "Configure your Web Part",
    "PlaceholderDescription": "Please configure the Web Part to show the Power Apps Canvas App by specify the App Web Link in the Web Part configuration. The App Web Link (with domain equal to \"apps.powerapps.com\" or \"apps.gov.powerapps.us\") can be found in the Power Apps Canvas App's Properties.",
    "PlaceholderButtonLabel": "Configure",
    "UseCustomHeightLabel": "Use Custom Height",
    "CustomHeightLabel": "Custom Height",
    "ThemeColorsParamPrefixLabel": "Theme Colors Parameters Prefix",
  }
});